### ISSUE TITLE
Contributor-friendliness roadmap

### ISSUE THREAD

**Issue by Goldob** [NPGuys/NPGuys#1]
Inspired by the upcoming [Hacktoberfest](https://github.com/blog/2433-celebrate-open-source-this-october-with-hacktoberfest), I've decided to bring this project back to life. I'm flattered by the amount of positive feedback it receives, even after all this time, and I feel guilty for not being able to meet the community's demands. What makes it even worse is that I've actually received some help offers - which I'm very grateful for - but which I was not prepared to handle.

That said, I'm going to take a series of steps to prepare a path for anyone willing to contribute. At this stage, any help would be very valuable and that's why I would like to make it as frictionless experience as possible. Here's the plan:

- [x] automate dependency management & build process
- [x] set up continuous integration
- [ ] prepare tests for where it's appropriate
- [ ] create `README.md` and `CONTRIBUTING.md` files for newcomers
- [ ] create issue & pull request templates
- [ ] create wiki with project documentation
- [ ] create project website with [GitHub Pages](https://pages.github.com/)

When this is done, I hope it will get easier for anyone with minimal Java experience to start tinkering on the project. Who knows, maybe I'll even find someone to maintain the project with me.

Keep posted. I'm counting on you :heart:

**Comment by Rolimao** [comment]
Could you fix problems with skillapi scoreboard? 
Skillapi is covering npguys
